# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := unittest vm

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

unittest: vm
	@echo "==== Building unittest ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f unittest.make

vm: 
	@echo "==== Building vm ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f vm.make

clean:
	@${MAKE} --no-print-directory -C . -f unittest.make clean
	@${MAKE} --no-print-directory -C . -f vm.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   unittest"
	@echo "   vm"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
